steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--build-arg'
      - 'VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}'
      - '--build-arg'
      - 'VITE_SUPABASE_ANON_KEY=${_VITE_SUPABASE_ANON_KEY}'
      - '-t'
      - '${_IMAGE}:${COMMIT_SHA}'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}:${COMMIT_SHA}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE_NAME}'
      - '--image=${_IMAGE}:${COMMIT_SHA}'
      - '--region=${_REGION}'
images:
  - '${_IMAGE}:${COMMIT_SHA}'
options:
  logging: CLOUD_LOGGING_ONLY
